# Generated by Django 3.1 on 2021-07-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0030_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_name',
        ),
    ]
