# Generated by Django 3.1 on 2021-07-18 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0032_comment_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
