# Generated by Django 3.1 on 2021-07-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0034_auto_20210718_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.TextField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
